alias ls='eza --icons'
alias ll='eza -la --icons'
alias lt='eza --tree --icons --level=2'
alias la='eza -a --icons'
alias cat='batcat'
alias fd='fdfind'
alias lg='lazygit'
alias lzd='lazydocker'
alias vim='nvim'
alias v='nvim'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias gs='git status'
alias gd='git diff'
alias gl='git log --oneline --graph'
